name: guthubui.xogames.org
env:
  PROJECT: guthubui
  HOST: xogames.org

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: copy build files via ssh
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ env.HOST }}
        username: ${{ secrets.USERNAME }}
        timeout: 5m
        key: ${{ secrets.DEPLOYMENT_USER_KEY }}
        source: "build/*,githubui.caddy"
        target: "~/sites-enabled/"
