name: guthubui.xogames.org
env:
  PROJECT: guthubui
  HOST: xogames.org

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOYMENT_USER_KEY }}
        script: |
          mkdir -p ~/${{ env.PROJECT }}.${{ env.HOST }}/public_html/
    - uses: actions/checkout@v3
    - name: copy build files via ssh
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ env.HOST }}
        username: ${{ secrets.USERNAME }}
        timeout: 120s 
        key: ${{ secrets.DEPLOYMENT_USER_KEY }}
        source: "build/*"
        target: "~/${{ env.PROJECT }}.${{ env.HOST }}/"
